---
- name: Create user and grant sudo permissions
  hosts: all
  become: yes
  vars:
    new_username: user1
    sudo_group: sudo  # You can adjust this based on your system (e.g., wheel for some distributions)
  tasks:
    - name: Ensure the user is created
      user:
        name: "{{ new_username }}"
        state: present
        createhome: yes
        shell: /bin/bash
      become: yes

    - name: Add user to sudoers file
      lineinfile:
        dest: /etc/sudoers
        line: "{{ new_username }} ALL=(ALL) NOPASSWD:ALL"
        validate: 'visudo -cf %s'
        state: present
        backup: yes
      become: yes
      become_method: sudo

