---
- name: Append new line in sudoers file with empty lines before and after
  hosts: 192.168.56.12
  become: yes
  tasks:
    - name: Add empty line before the new line in sudoers file
      lineinfile:
        path: /etc/sudoers
        line: ''
        insertafter: EOF
      become: yes

    - name: Append new line in sudoers file
      lineinfile:
        path: /etc/sudoers
        line: "sree ALL=(ALL) NOPASSWD:ALL"
        insertafter: EOF
      become: yes

    - name: Add empty line after the new line in sudoers file
      lineinfile:
        path: /etc/sudoers
        line: ''
        insertafter: "sree ALL=(ALL) NOPASSWD:ALL"
      become: yes
