---
- name: Create user and grant sudo access as root
  hosts: your_target_host
  become: yes
  vars:
    new_username: sree
    first_line: '####Local-Users#####'
    second_line: '## Allows members of'
  tasks:
    - name: Ensure the user is created
      user:
        name: "{{ new_username }}"
        state: present
        createhome: yes
        shell: /bin/bash
      become: yes

    - name: Add user to sudoers file with root privileges
      lineinfile:
        dest: /etc/sudoers
        line: "{{ new_username }} ALL=(ALL:ALL) NOPASSWD:ALL"
        after: "{{ first_line }}"
        validate: 'visudo -cf %s'
        state: present
        backup: yes
      become: yes
      become_method: sudo

    - name: Move the user entry below the second line
      lineinfile:
        dest: /etc/sudoers
        regexp: '^{{ new_username }}'
        line: "{{ new_username }} ALL=(ALL:ALL) NOPASSWD:ALL"
        insertafter: "{{ second_line }}"
        state: present
      become: yes
      become_method: sudo
