---
- name: Create user and grant sudo access as root
  hosts: your_target_host
  become: yes
  vars:
    new_username: sree
    sudoers_file: '/etc/sudoers'
  tasks:
    - name: Ensure the user is created
      user:
        name: "{{ new_username }}"
        state: present
        createhome: yes
        shell: /bin/bash
      become: yes

    - name: Add new user entry with one empty line below '####Local-Users#####' in sudoers file
      blockinfile:
        path: "{{ sudoers_file }}"
        marker: "# {mark} ANSIBLE MANAGED BLOCK - {{ new_username }}"
        block: |
          sree ALL=(ALL) NOPASSWD:ALL
        insertafter: '####Local-Users#####'
      become: yes
