---
- name: Create user and grant sudo access as root
  hosts: 192.168.56.12
  become: yes
  vars:
    new_username: sree
    first_line: '####Local-Users#####'
    second_line: 'ansibleid'
    sudoers_file: '/etc/sudoers'
  tasks:
    - name: Ensure the user is created
      user:
        name: "{{ new_username }}"
        state: present
        createhome: yes
        shell: /bin/bash
      become: yes

    - name: Insert new user entry between specified lines in sudoers file
      lineinfile:
        path: "{{ sudoers_file }}"
        line: "{{ new_username }} ALL=(ALL:ALL) NOPASSWD:ALL"
        insertafter: "{{ first_line }}"
        insertbefore: "{{ second_line }}"
        validate: 'visudo -cf %s'
        state: present
      become: yes
