---
- name: Create user and grant sudo access as root
  hosts: 192.168.56.12
  become: yes
  vars:
    new_username: sree
    first_line: '####Local-Users#####'
    second_line: '## Allows members'
    sudoers_file: '/etc/sudoers'
  tasks:
    - name: Ensure the user is created
      user:
        name: "{{ new_username }}"
        state: present
        createhome: yes
        shell: /bin/bash
      become: yes

    - name: Insert new user entry after the first line in sudoers file
      lineinfile:
        path: "{{ sudoers_file }}"
        insertafter: "{{ first_line }}"
        line: "{{ new_username }} ALL=(ALL) NOPASSWD:ALL"
        state: present
      become: yes

    - name: Add an extra line after the new user's entry
      lineinfile:
        path: "{{ sudoers_file }}"
        insertafter: "{{ new_username }} ALL=(ALL) NOPASSWD:ALL"
        line: ' '
        state: present
      become: yes

    - name: Move the new user entry before the second line in sudoers file
      lineinfile:
        path: "{{ sudoers_file }}"
        regexp: '^{{ new_username }}'
        insertbefore: "{{ second_line }}"
        state: present
      become: yes
