---
- name: Insert new line between two specific lines with one empty line
  hosts: 192.168.56.12
  become: yes
  tasks:
    - name: Add empty line before the new line in sudoers file
      lineinfile:
        path: /etc/sudoers
        line: ''
        insertafter: "ansibleid "
      become: yes

    - name: Insert new line in sudoers file
      lineinfile:
        path: /etc/sudoers
        line: "sree ALL=(ALL) NOPASSWD:ALL"
        insertafter: "ansibleid "
      become: yes

    - name: Add empty line after the new line in sudoers file
      lineinfile:
        path: /etc/sudoers
        line: ''
        insertafter: "sree ALL=(ALL) NOPASSWD:ALL"
      become: yes

