---
- name: Create user and grant sudo access as root
  hosts: 192.168.56.12
  become: yes
  vars:
    new_username: sree
    sudoers_file: '/etc/sudoers'
  tasks:
    - name: Ensure the user is created
      user:
        name: "{{ new_username }}"
        state: present
        createhome: yes
        shell: /bin/bash
      become: yes

    - name: Add new user entry with empty lines before and after the block starts in sudoers file
      blockinfile:
        path: "{{ sudoers_file }}"
        marker: "# {mark} ANSIBLE MANAGED BLOCK - {{ new_username }}"
        block: |
          sree ALL=(ALL) NOPASSWD:ALL
        insertafter: '####Local-Users#####'
        insertbefore: 'sree ALL=(ALL) NOPASSWD:ALL'
        before_block: |
          ''
        after_block: |
          ''
      become: yes
