---
- name: Update China servers and manage sudo permissions
  hosts: all
  become: yes  # Indicate that we need root privileges to execute tasks

  tasks:
    - name: Create awscnadmin user
      user:
        name: awscnadmin
        state: present

    # - name: Make sudoers.d/hilton-users mutable
    #   command: chattr -i /etc/sudoers.d/hilton-users
    #   become: yes

    - name: Ensure comment line above awscnadmin entry
      lineinfile:
        path: /etc/sudoers.d/
        insertafter: EOF
        line: "# user rules for awscnadmin netgroup"
      become: yes

    - name: Insert awscnadmin entry below awsadmin and before service-now intake discovery
      lineinfile:
        path: /etc/sudoers.d/
        insertafter: EOF
        line: "+awscnadmin ALL=(ALL:ALL) ALL"
      become: yes

    # - name: Make sudoers.d/hilton-users immutable
    #   command: chattr +i /etc/sudoers.d/hilton-users
    #   become: yes

    # - name: Make access.netgroup.conf mutable
    #   command: chattr -i /etc/security/access.netgroup.conf
    #   become: yes

    # - name: Ensure correct line in access.netgroup.conf
    #   lineinfile:
    #     path: /etc/security/access.netgroup.conf
    #     insertafter: "^\\+ : @nttunixawsadmins: ALL$"
    #     line: "+ : @nttunixawscnadmins : ALL"
    #   become: yes